before_script:
    - echo ${NPMRC} > ~/.npmrc
    - export VERSION=$(node -p "require('./package.json').version")
    - export DEVELOP_VERSION=$VERSION-$CI_COMMIT_REF_SLUG-$CI_JOB_ID
    - export RELEASE_VERSION=$VERSION-RELEASE
    - export RELEASE_BRANCH=release/$VERSION
    - export GITURL=https://imd:${GITLAB_TOKEN}@gitlab.transmit.im/sdk/calls/server-api-calls-sdk.git

build_android_release:
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: build
    only:
        - /release/.*/
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew build
    artifacts:
        paths:
        - "build/libs/*.jar"

        
publish_android_release:
    when: manual
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: deploy
    only:
        - /release/.*/
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew publish
    dependencies: 
        - build_android_release
        