build_android:
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: build
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew build
    artifacts:
        paths:
        - "build/libs/*.jar"

publish_android:
    when: manual
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: deploy
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew publish
    dependencies: 
        - build_android

build_npm:
    stage: build
    image: node
    script:
        - yarn
    artifacts:
        paths:
            - npm

publish_npm:
    stage: deploy
    image: node
    when: manual
    script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > ~/.npmrc
        - export RELEASE_VERSION=$(node -p "require('./package.json').version")
        - (if [ $CI_COMMIT_REF_SLUG == "master" ]; then export DEVELOP_VERSION=$RELEASE_VERSION; else DEVELOP_VERSION=$RELEASE_VERSION-$CI_COMMIT_REF_SLUG-$CI_JOB_ID; fi)
        - cd npm
        - sed -Ei 's/VERSION/'$DEVELOP_VERSION'/g' package.json
        - (if [ $CI_COMMIT_REF_SLUG == "master" ]; then publish --tag=latest; else publish --tag=$CI_COMMIT_REF_SLUG-latest; fi)
        - cat package.json
    dependencies: 
        - build_npm