stages:
  - build
  - check
  - deploy

build_android:
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: build
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew build
    artifacts:
        paths:
        - "build/libs/*.jar"

build_npm:
    stage: build
    image: node
    script:
        - npm install
        - npm run-script install
    artifacts:
        paths:
            - npm

publish:
    stage: check
    when: manual
    script:
        - echo "publish"
    allow_failure: false
    dependencies: 
        - build_android
        - build_npm

publish_npm:
    except:
        - master
    stage: deploy
    script:
        #- export DEVELOP_VERSION=$VERSION-$CI_COMMIT_REF_SLUG-$CI_JOB_ID
        #- cd build/npm
        #- sed -Ei 's/VERSION/'$DEVELOP_VERSION'/g' package.json
        #- npm publish --tag=$CI_COMMIT_REF_SLUG-latest
        - echo "publish_npm"
    dependencies: 
        - publish

publish_android:
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: deploy
    script:
        #- echo "mavenUser=${NEXUSUSER}" > gradle.properties
        #- echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        #- ./gradlew publish
        - echo "publish_android"
    dependencies: 
        - publish
