
build_android:
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: build
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew build
    artifacts:
        paths:
        - "build/libs/*.jar"

build_npm:
    stage: build
    image: node
    script:
        - npm install
        - npm run-script install
    artifacts:
        paths:
            - npm

publish:
    when: manual
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: deploy
    script:
        - ls -l npm
        - ls -l build/libs
    dependencies: 
        - build_android
        - build_npm
