stages:
    - build
    - publish
    - deploy

before_script:
    - echo ${NPMRC} > ~/.npmrc
    - export VERSION=$(node -p "require('./package.json').version")
    - export DEVELOP_VERSION=$VERSION-$CI_COMMIT_REF_SLUG-$CI_JOB_ID
    - export RELEASE_VERSION=$VERSION-RELEASE
    - export RELEASE_BRANCH=release/$VERSION
    - export GITURL=https://imd:${GITLAB_TOKEN}@gitlab.transmit.im/sdk/calls/server-api-calls-sdk.git

build_npm:
    stage: build
    image: node
    except:
        - /release/.*/
        - master
    script:
        - npm install
        - npm run-script install
        - cd npm
        - sed -Ei 's/VERSION/'$DEVELOP_VERSION'/g' package.json
        - echo $(node -p "require('./package.json').version")
    artifacts:
        paths:
            - npm

build_android:
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: build
    except:
        - /release/.*/
        - master
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew build
    artifacts:
        paths:
        - "build/libs/*.jar"

publish:
    stage: publish
    when: manual
    allow_failure: true
    except:
        - /release/.*/
        - master
    script:
        - echo "publish"
    dependencies: 
        - build_android
        - build_npm

publish_npm:
    stage: deploy
    except:
        - /release/.*/
        - master
    script:
        - cd npm
        - npm publish --tag=$CI_COMMIT_REF_SLUG-latest
    dependencies:
        - publish
        
publish_android:
    when: manual
    image: gitlab.transmit.im:5001/gitlab/builders/server-builder:latest
    stage: deploy
    script:
        - echo "mavenUser=${NEXUSUSER}" > gradle.properties
        - echo "mavenPassword=${NEXUSPASS}" >> gradle.properties
        - ./gradlew publish
    dependencies: 
        - publish
        